In [15]:
#pip install nhanes #instalar las librerias desde cmd
#pip install pyjanitor #librerias para limpieza de datos

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nhanes.load
import sklearn.compose
import sklearn.preprocessing
import janitor

#Cargamos nuestro dataset
display(nhanes.load.load_NHANES_data(year="2017-2018"))

nhanes_raw_df = (
    nhanes.load.load_NHANES_data(year="2017-2018")
    .clean_names(
        case_type="snake"
    )
)
display(nhanes_raw_df.head(2))

#Creamos un datagrame más pequeño
nhanes_df =  (
    nhanes_raw_df.select_columns(
        "general_health_condition",
        "age_in_years_at_screening",
        "gender"
    )
).rename_columns(
    {
        "age_in_years_at_screening":"age"
    }
)
display(nhanes_df)

#Codificación ordinal con sklearn 
X = [["Male"],["Female"],["Female"]]
display(X)

encoder = sklearn.preprocessing.OrdinalEncoder()
encoder.fit_transform(X)
encoder.categories_
encoder.inverse_transform([[1],[0],[0]])

nhanes_df.dtypes

categorical_columns=nhanes_df.select_dtypes(object).columns
display(categorical_columns)

#Creamos un transformador para la codificación

categorical_transformer = sklearn.compose.make_column_transformer(
    (sklearn.preprocessing.OrdinalEncoder(),categorical_columns),
    remainder="passthrough"
)

#Aplicamos el transformador a nuestro dataset
nhanes_transformed_df = (
    pd.DataFrame(
        categorical_transformer.fit_transform(nhanes_df),
        columns = categorical_transformer.get_feature_names_out(),
        index=nhanes_df.index
    )
    .rename_columns(
        function = lambda x:x.removeprefix("ordinalencoder__")
    )
    .rename_columns(
        function = lambda x:x.removeprefix("remainder__")
    )
)
display(nhanes_transformed_df)

,GeneralHealthCondition,EverBreastfedOrFedBreastmilk,AgeStoppedBreastfeedingdays,AgeFirstFedFormuladays,AgeStoppedReceivingFormuladays,AgeStartedOtherFoodbeverage,AgeFirstFedMilkdays,TypeOfMilkFirstFedWholeMilk,TypeOfMilkFirstFed2Milk,TypeOfMilkFirstFed1Milk,...,DaysSmokedCigsDuringPast30Days,AvgCigarettesdayDuringPast30Days,TriedToQuitSmoking,TimesStoppedSmokingCigarettes,HowLongWereYouAbleToStopSmoking,UnitOfMeasureDayweekmonthyear_2_SMQ,CurrentSelfreportedHeightInches,CurrentSelfreportedWeightPounds,TriedToLoseWeightInPastYear,TimesLost10LbsOrMoreToLoseWeight
SEQN,,,,,,,,,,,,,,,,,,,,,
93703.0,NaN,1.0,273.0,1.0,365.0,152.0,365.0,Whole or regular milk,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93704.0,NaN,1.0,60.0,3.0,365.0,126.0,365.0,Whole or regular milk,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93705.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,63.0,165.0,0.0,11 times or more
93706.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,145.0,0.0,Never
93707.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102952.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.0,0.0,Never
102953.0,Fair or,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,65.0,218.0,0.0,Never
102954.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,66.0,150.0,0.0,Never
102955.0,Very good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102956.0,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,20.0,1.0,1.0,2.0,Days,69.0,250.0,0.0,1 to 2

,general_health_condition,ever_breastfed_or_fed_breastmilk,age_stopped_breastfeedingdays,age_first_fed_formuladays,age_stopped_receiving_formuladays,age_started_other_foodbeverage,age_first_fed_milkdays,type_of_milk_first_fed_whole_milk,type_of_milk_first_fed2_milk,type_of_milk_first_fed1_milk,...,days_smoked_cigs_during_past30_days,avg_cigarettesday_during_past30_days,tried_to_quit_smoking,times_stopped_smoking_cigarettes,how_long_were_you_able_to_stop_smoking,unit_of_measure_dayweekmonthyear_2_smq,current_selfreported_height_inches,current_selfreported_weight_pounds,tried_to_lose_weight_in_past_year,times_lost10_lbs_or_more_to_lose_weight
SEQN,,,,,,,,,,,,,,,,,,,,,
93703.0,NaN,1.0,273.0,1.0,365.0,152.0,365.0,Whole or regular milk,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93704.0,NaN,1.0,60.0,3.0,365.0,126.0,365.0,Whole or regular milk,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

C:\Users\ingma\anaconda3\lib\site-packages\pandas_flavor\register.py:153: FutureWarning: This function will be deprecated in a 1.x release. Please use `jn.select` instead.
  return method(self._obj, *args, **kwargs)
C:\Users\ingma\anaconda3\lib\site-packages\pandas_flavor\register.py:153: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.rename` instead.
  return method(self._obj, *args, **kwargs)

         general_health_condition   age  gender
SEQN
93703.0                       NaN   2.0  Female
93704.0                       NaN   2.0    Male
93705.0                      Good  66.0  Female
93706.0                 Very good  18.0    Male
93707.0                      Good  13.0    Male
...                           ...   ...     ...
102952.0                Very good  70.0  Female
102953.0                  Fair or  42.0    Male
102954.0                     Good  41.0  Female
102955.0                Very good  14.0  Female
102956.0                     Good  38.0    Male

[8366 rows x 3 columns]

[['Male'], ['Female'], ['Female']]

Index(['general_health_condition', 'gender'], dtype='object')

C:\Users\ingma\anaconda3\lib\site-packages\pandas_flavor\register.py:153: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.rename` instead.
  return method(self._obj, *args, **kwargs)
C:\Users\ingma\anaconda3\lib\site-packages\pandas_flavor\register.py:153: FutureWarning: This function will be deprecated in a 1.x release. Please use `pd.DataFrame.rename` instead.
  return method(self._obj, *args, **kwargs)

          general_health_condition  gender   age
SEQN
93703.0                        NaN     0.0   2.0
93704.0                        NaN     1.0   2.0
93705.0                        2.0     0.0  66.0
93706.0                        4.0     1.0  18.0
93707.0                        2.0     1.0  13.0
...                            ...     ...   ...
102952.0                       4.0     0.0  70.0
102953.0                       1.0     1.0  42.0
102954.0                       2.0     0.0  41.0
102955.0                       4.0     0.0  14.0
102956.0                       2.0     1.0  38.0

[8366 rows x 3 columns]