In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd
df_books = pd.read_csv('/content/drive/MyDrive/Curso_Ciencia_de_Datos /libros.csv')
df_books.head(2)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

## Slicing

In [11]:
df_books[0:12]

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
11,A Patriot's History of the United States: From...,Larry Schweikart,4.6,460,2,2010,Non Fiction

In [8]:
df_books[['Name','Author']]

,Name,Author
0,10-Day Green Smoothie Cleanse,JJ Smith
1,11/22/63: A Novel,Stephen King
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson
3,1984 (Signet Classics),George Orwell
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids
...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero

## LOC

In [9]:
df_books.loc[0:4,['Name','Author']]

                                                Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [10]:
df_books.loc[:,['Reviews']] * -1

     Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [12]:
df_books.loc[:,['Author']] == 'JJ Smith'

     Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

## ILOC

In [15]:
df_books.iloc[0:2,0:4]

                            Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

In [16]:
df_books.iloc[1,3] * -1

-2052

In [17]:
df_books.iloc[:2,2:5]

   User Rating  Reviews  Price
0          4.7    17350      8
1          4.6     2052     22